build:
  version: "2.0"

loans:
  message: "Welcome to the course about microservices related to QA APIs"
  contactDetails:
    name: "Juanito - QA"
    email: "juanito@email.com"
  onCallSupport:
    - 677777777
    - 688888888